### ISSUE TITLE
ng2-qgrid 9.2.1  is not working with @angular/cdk 11.2.0 and @angular/material 11.2.0

### ISSUE THREAD

**Issue by prathyukurra** [qgrid/ng2#520]
Is latest version of angular and material (11.2.0) is compatible with ng2-qgrid??

I was updating from  angular 8 to 11.2.0 and its dependencies. I did follow Angular Update Guide.

1. Initially updated from angular 8 to 9 and material 8 to 9
2. Next updated from angular 9 to 10 and material 9 to 10
3.  finally to latest versions 11.2.0
4. Then updated all the packages to latest versions including ng2-qgrid to 9.2.1.

But I see the the following errors when I build the application.

Error: ./node_modules/ng2-qgrid/theme/material/fesm2015/ng2-qgrid-theme-material.js 6281:858-866
"export '_MatMenu' was not found in '@angular/material/menu'
    at HarmonyImportSpecifierDependency._getErrors (C:\app-name\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (C:\app-name\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (C:\app-name\node_modules\webpack\lib\Compilation.js:1463:22)
    at C:\app-name\node_modules\webpack\lib\Compilation.js:1258:10
    at _next0 (eval at create (C:\app-name\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:43:1)
    at eval (eval at create (C:\app-name\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:57:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./projects/emr/src/app/features/spaces/space.module.ts
 @ ./projects/emr/src/app/app.module.ts
 @ ./projects/emr/src/main.ts
 @ multi ./projects/emr/src/main.ts

Error: ./node_modules/ng2-qgrid/theme/material/fesm2015/ng2-qgrid-theme-material.js 422:6-26
"export 'ɵɵstaticContentQuery' was not found in '@angular/core'
    at HarmonyImportSpecifierDependency._getErrors (C:\app-name\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (C:\app-name\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (C:\app-name\node_modules\webpack\lib\Compilation.js:1463:22)
    at C:\app-name\node_modules\webpack\lib\Compilation.js:1258:10
    at _next0 (eval at create (C:\app-name\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:43:1)
    at eval (eval at create (C:\app-name\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:57:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./projects/emr/src/app/features/spaces/space.module.ts
 @ ./projects/emr/src/app/app.module.ts
 @ ./projects/emr/src/main.ts
 @ multi ./projects/emr/src/main.ts

Let me know if I am missing anything or do I need to follow different steps?

**Comment by prathyukurra** [comment]
Is NG2grid is working with angular 11 yet?

**Comment by klumba12** [comment]
Hey, yes it should work, please consider installing the latest version, sorry for the late response.
